# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-29 01:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bourbon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BourbonID', models.CharField(max_length=200)),
                ('Bourbon', models.CharField(max_length=200)),
                ('Aged', models.IntegerField()),
                ('Proof', models.IntegerField()),
                ('Corn', models.IntegerField()),
                ('Rye', models.IntegerField()),
                ('Barley', models.IntegerField()),
                ('Wheat', models.IntegerField()),
                ('Type', models.CharField(max_length=200)),
                ('Style', models.CharField(max_length=200)),
                ('Price_Range', models.IntegerField()),
                ('Distillery', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Website', models.URLField()),
                ('Description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RatingID', models.IntegerField(blank=True, null=True)),
                ('Pub_Date', models.DateTimeField(verbose_name='date published')),
                ('User_Name', models.CharField(max_length=100)),
                ('Comment', models.CharField(max_length=200)),
                ('Rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('Bourbon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourbonsite.Bourbon')),
            ],
        ),
    ]
